<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PilihOS</name>
   <tag></tag>
   <elementGuidId>7b0ac3f0-dd5c-4d94-9b20-0e4ee629d6ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'ng-option')]//span[normalize-space()='OS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'ng-option')]//span[normalize-space()='OS']</value>
      <webElementGuid>641008bc-f721-4fd3-b214-e437dc382cee</webElementGuid>
   </webElementProperties>
</WebElementEntity>
