<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BtnTambahSubject</name>
   <tag></tag>
   <elementGuidId>4787ba0b-a0d4-4623-9602-e2c08f5fdd3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='buttonAddDocument']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;buttonAddDocument&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Tambah Subjectivity$/ >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2635649-e9b1-42e4-a5dc-d32ec8b15417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e48c8848-7048-428f-958b-072e3e84219f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buttonAddDocument</value>
      <webElementGuid>c906786c-2d69-4586-b99c-aee424f2d8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ButtonAdd</value>
      <webElementGuid>0e7c946a-a7f4-41e3-8c24-be3216499399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMainDashboard&quot;)/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;DivTableContainer DivTableContainerAcceptation&quot;]/div[@class=&quot;DivAddListDetail ng-star-inserted&quot;]/input[@class=&quot;ButtonAdd&quot;]</value>
      <webElementGuid>ce3105a8-3b23-4841-870f-4ed6bff408e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='buttonAddDocument']</value>
      <webElementGuid>3462489d-7794-45df-95a9-a16ea04c4cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[5]/div/input</value>
      <webElementGuid>3b40a22c-035a-493a-8737-03723a21dbc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>86288346-7b53-4386-9fd5-7dd7a1badf1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'buttonAddDocument']</value>
      <webElementGuid>a16e469d-88a0-4d2a-b2a5-f8eb2fc805e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
