<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date2</name>
   <tag></tag>
   <elementGuidId>cd1bb446-b631-4b16-bc07-bb874d6f0a7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@placeholder='Date'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@placeholder='Date'])[1]</value>
      <webElementGuid>f3e5f79c-6d04-42d7-b54f-99480f895610</webElementGuid>
   </webElementProperties>
</WebElementEntity>
