<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Catatan</name>
   <tag></tag>
   <elementGuidId>e5a26fd3-da9b-4f6d-996a-81c67a5285a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textModelCOBSubmissionDetailPageClosingInstructionNote</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textModelCOBSubmissionDetailPageClosingInstructionNote']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukan Catatan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>246dd02c-f244-4099-8d0f-6774ff555d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPageClosingInstructionNote </value>
      <webElementGuid>c7ec6786-0a50-438b-9ece-ce63d5ee6d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textModelCOBSubmissionDetailPageClosingInstructionNote</value>
      <webElementGuid>c39eaf31-118e-4203-8c16-c60a01f49ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Catatan</value>
      <webElementGuid>0a255dd1-855c-45ac-9a93-f566d6ad951a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-touched</value>
      <webElementGuid>f538397d-8fc2-4cd3-86eb-6a5005c10696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textModelCOBSubmissionDetailPageClosingInstructionNote&quot;)</value>
      <webElementGuid>5256f7c0-fbe7-4c51-bb80-23b208bf72c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textModelCOBSubmissionDetailPageClosingInstructionNote']</value>
      <webElementGuid>a58718c6-d1d4-4616-88cc-32d5333d5fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ClosingInstruction']/form/div/fieldset/textarea</value>
      <webElementGuid>5ceccff0-0b74-40f5-a9e7-0550e6502db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>5ee9ed16-5492-4946-bd56-e7068cf45397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ModelCOBSubmissionDetailPageClosingInstructionNote ' and @id = 'textModelCOBSubmissionDetailPageClosingInstructionNote' and @placeholder = 'Masukan Catatan']</value>
      <webElementGuid>014d7593-df2f-4070-abb1-f7d956fb0291</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
