<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputSubjectivityNote</name>
   <tag></tag>
   <elementGuidId>bd02d427-e69e-46c0-a07e-4e4ac9bb4117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='textAreaSubjectivityNote']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;textAreaSubjectivityNote&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea[name=&quot;textAreaSubjectivityNote&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>370f6f6d-b4de-4efa-b34c-bb037855e8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textAreaSubjectivityNote</value>
      <webElementGuid>d17794d3-ec2f-4898-948f-fd92bb388faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textareaCob ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>bcac802f-62fa-4676-b14b-0439f85039bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMainDashboard&quot;)/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;DivTableContainer DivTableContainerAcceptation&quot;]/table[@class=&quot;TableListDetailsAttachment&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;TableDataInput ng-star-inserted&quot;]/textarea[@class=&quot;textareaCob ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>d6c92bb4-65c7-42ad-aceb-e5c864a33a77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='textAreaSubjectivityNote']</value>
      <webElementGuid>cc4c855f-90e0-4330-aa07-1ef5ad74aec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[5]/table/tbody/tr[2]/td[2]/textarea</value>
      <webElementGuid>eab481aa-9890-4f70-9f46-cd46f2e259dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/textarea</value>
      <webElementGuid>4abe3090-6d10-4b36-95bd-08fabf4bfa48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'textAreaSubjectivityNote']</value>
      <webElementGuid>d8b7b21a-3e26-40ae-84c0-8766e08b14c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
