<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox6</name>
   <tag></tag>
   <elementGuidId>0b3a4cf1-d523-4a28-afee-4390e29a96fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkBox5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkBox5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#checkBox5</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4dce55c-80c5-4a8f-bdd5-19f4118683ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9c11a870-2dc6-42b7-b29c-09bfbd3cd8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkBox5</value>
      <webElementGuid>5ba1ed0a-5a9b-4bd5-bc33-aefb01357801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkBox5</value>
      <webElementGuid>df063283-5d5a-4556-8305-a781fe5c1c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>f7e4df4c-c0bf-46aa-89fd-71aa7b014da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkBox5&quot;)</value>
      <webElementGuid>cefdae39-ef81-4e84-aa0c-591b6e99d0b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkBox5']</value>
      <webElementGuid>1be3aa1a-efe2-498d-b06a-c81b1eb3812c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[5]/table/tbody/tr[6]/td/input</value>
      <webElementGuid>2f283001-6b2e-4e87-adc1-88eb1d7f4f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/input</value>
      <webElementGuid>b29b738f-e2d2-4f6f-8995-b8ca7b51017d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'checkBox5' and @id = 'checkBox5']</value>
      <webElementGuid>25715d0d-66ae-427e-b817-3153c5a891e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
