<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubDetail By Septian</name>
   <tag></tag>
   <elementGuidId>f446d513-5b71-4ae4-a2f3-8e8f8f3c6fbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divMainDashboard']/div/table/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;BN57/1861/UND/WS-0114/SMG/11/25&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6a4165d8-a1b4-4f1b-930d-39520b7e95d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BN57/1861/UND/WS-0114/SMG/11/25</value>
      <webElementGuid>7f07e93a-d0a3-4287-9089-d0de05ff4edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMainDashboard&quot;)/div[@class=&quot;DivTableContainer&quot;]/table[1]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[2]</value>
      <webElementGuid>b0aadbd6-f87a-4cbe-99c4-ea7941c6cc36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/div/table/tbody/tr/td[2]</value>
      <webElementGuid>7fcf9bbb-80a4-4162-b8df-1e6f4737ac08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Penerbitan Polis'])[2]/following::td[2]</value>
      <webElementGuid>07bfa244-2d88-46ec-8d8f-150df234792e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Pengajuan Relationship Manager'])[1]/following::td[2]</value>
      <webElementGuid>556d54be-1570-4de9-93f3-73aa58c9232a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::td[1]</value>
      <webElementGuid>acfc7f96-f734-4701-99c1-add926217e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Automation QA2'])[1]/preceding::td[2]</value>
      <webElementGuid>3d5e858c-7539-4a2c-b0ce-4699705e6630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BN57/1861/UND/WS-0114/SMG/11/25']/parent::*</value>
      <webElementGuid>b5241079-18ad-435f-bf7b-fe856ab725d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>3ec0e8f5-352a-4468-899f-f266fba06f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'BN57/1861/UND/WS-0114/SMG/11/25' or . = 'BN57/1861/UND/WS-0114/SMG/11/25')]</value>
      <webElementGuid>a50cd487-eedf-4e91-8d4e-c8ac010cdffd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
