<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubDetail By Ria Disposisi</name>
   <tag></tag>
   <elementGuidId>6a5b2374-b6cf-4ea3-9382-d2e7536af730</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divMainDashboard']/div/table/tbody/tr[10]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;BN57/1861/UND/WS-0114/SMG/11/25&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>fb6b1c56-de5e-48f4-9927-dd31990691bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BN57/1861/UND/WS-0114/SMG/11/25</value>
      <webElementGuid>226380e7-3fbc-477d-bbd2-16e8249c682f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMainDashboard&quot;)/div[@class=&quot;DivTableContainer&quot;]/table[1]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[2]</value>
      <webElementGuid>ede112d8-aa73-43fe-b162-0ee61389c1db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/div/table/tbody/tr[10]/td[2]</value>
      <webElementGuid>4446dcbc-5f91-464b-8789-656d8f1d6836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waiting disposition by OJS'])[9]/following::td[2]</value>
      <webElementGuid>e85dd5da-f3bd-4bd3-820c-f78e0c1ccb99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='John Doe'])[1]/following::td[5]</value>
      <webElementGuid>f98c103e-9d22-454e-85b1-474ec9c75169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[9]/preceding::td[1]</value>
      <webElementGuid>c6ca9ff8-a91e-46cf-8529-a05affbf38ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Automation QA2'])[1]/preceding::td[2]</value>
      <webElementGuid>8dc4421d-d917-4390-885e-db5bef0a402d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BN57/1861/UND/WS-0114/SMG/11/25']/parent::*</value>
      <webElementGuid>4c806c85-b199-48cc-ab6b-2aea63cceed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]</value>
      <webElementGuid>9219f4de-2686-42f1-8093-0aa7874de67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'BN57/1861/UND/WS-0114/SMG/11/25' or . = 'BN57/1861/UND/WS-0114/SMG/11/25')]</value>
      <webElementGuid>58ace27c-5b08-4893-833b-58f8b619cac6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
