<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubMenuMonitor</name>
   <tag></tag>
   <elementGuidId>a832bf76-bc3f-4967-9902-ade4affb1e5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-home/div/nav/ul/li[14]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-home/div/nav/ul/li[14]/ul/li[3]/a</value>
      <webElementGuid>a403f48e-6e84-4ed6-adc4-d1f0c48c1c24</webElementGuid>
   </webElementProperties>
</WebElementEntity>
