<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BtnDraft</name>
   <tag></tag>
   <elementGuidId>e569f1b2-2746-4a4e-8643-26a0a47f6acd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='buttonConfirmation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;buttonConfirmation&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Draft&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3df2879d-4e05-45d7-b35f-09814ae219f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8d87e22e-9939-49c2-b139-94b41f04d93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buttonConfirmation</value>
      <webElementGuid>96a750f4-0d89-40f5-b4cb-07dda263621c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>8f732330-0812-42c3-93b2-fc08a8d29d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ButtonSubmit</value>
      <webElementGuid>47405711-f5a7-4dae-a5b3-ec8bbc3302f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMainDashboard&quot;)/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;DivFormButtonContainer ng-star-inserted&quot;]/input[@class=&quot;ButtonSubmit&quot;]</value>
      <webElementGuid>dedce6a0-4f50-49b4-a166-7d11f3081de5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='buttonConfirmation']</value>
      <webElementGuid>743dbb34-b81b-457a-b1cb-824676fd8bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[12]/input[2]</value>
      <webElementGuid>7b872290-48b2-44df-9333-3f512ed6b3cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/input[2]</value>
      <webElementGuid>bf62ba2d-b8fb-48b3-ac4f-d9668b4d21a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'buttonConfirmation']</value>
      <webElementGuid>cf6b736e-5964-416c-b880-4b28a2c91b68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
