<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date3</name>
   <tag></tag>
   <elementGuidId>0b7589de-8649-4540-be59-edf06ac3aad9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@placeholder='Date'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@placeholder='Date'])[1]</value>
      <webElementGuid>d19e272c-f053-4f9e-a603-d548a48a67d7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
