<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputSubjectKet</name>
   <tag></tag>
   <elementGuidId>f570042c-e326-4931-b4d7-5de278e65840</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='textAreaSubjectivityDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;textAreaSubjectivityDescription&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea[name=&quot;textAreaSubjectivityDescription&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>31622ea3-179b-4f1d-9b3f-21d0b10c77d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textAreaSubjectivityDescription</value>
      <webElementGuid>dd8689cc-5d25-4460-b017-ab9dbb2df4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textareaCob ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>314d802d-b8d5-4f7b-937b-add5da0532a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMainDashboard&quot;)/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;DivTableContainer DivTableContainerAcceptation&quot;]/table[@class=&quot;TableListDetailsAttachment&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;TableDataInput ng-star-inserted&quot;]/textarea[@class=&quot;textareaCob ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>f6dfbaa3-5dde-4120-b92e-4883eb5ba2b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='textAreaSubjectivityDescription']</value>
      <webElementGuid>a02393e4-7305-4a65-8f73-2761e8b815d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[5]/table/tbody/tr[3]/td[7]/textarea</value>
      <webElementGuid>0c347c13-f0e8-49ad-8092-12102c2fe8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/textarea</value>
      <webElementGuid>e2a007e1-8c9a-40ef-b6c3-277ff97db0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'textAreaSubjectivityDescription']</value>
      <webElementGuid>2db3ed57-963d-4cba-8ac9-6541041965f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
