<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputSubjectivityNote</name>
   <tag></tag>
   <elementGuidId>d5c6c919-5d5b-4f59-8f0b-0fa6b4ce9684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='textAreaSubjectivityNote']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;textAreaSubjectivityNote&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea[name=&quot;textAreaSubjectivityNote&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9b34de01-3487-4e28-851f-b2ed0c2a4a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textAreaSubjectivityNote</value>
      <webElementGuid>dd702631-d8f2-4413-81d5-e9916fa2352d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textareaCob ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>48023276-58b8-4c54-ba34-2a401723a9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMainDashboard&quot;)/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;DivTableContainer DivTableContainerAcceptation&quot;]/table[@class=&quot;TableListDetailsAttachment&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;TableDataInput ng-star-inserted&quot;]/textarea[@class=&quot;textareaCob ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>35907adc-d9a6-4c8b-9d6a-f29532432746</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='textAreaSubjectivityNote']</value>
      <webElementGuid>10204d9c-4406-4858-9512-3173335779bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[5]/table/tbody/tr[2]/td[2]/textarea</value>
      <webElementGuid>1eee3aac-6a07-4a58-b5fe-c7bb9bae79c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/textarea</value>
      <webElementGuid>401d5a05-1435-406c-903a-8fdf00ccf14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'textAreaSubjectivityNote']</value>
      <webElementGuid>c729d10c-566f-46b1-84b7-ae2dae63f1e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
