<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>KT_InputTSI</name>
   <tag></tag>
   <elementGuidId>a3bea6fe-cbb9-47d6-a7d3-c30cd32e6895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputTSI']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputTSI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan TSI / Top Risk&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8175298-f672-49b6-b414-daf8aa56736c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f0d3456-f939-48e9-824c-5775ef6f382f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>separator.6</value>
      <webElementGuid>48452fe6-dc94-4995-ab1c-4022811896f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thousandseparator</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>c1296af3-81fd-4cc6-9caa-2489be382bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalmarker</name>
      <type>Main</type>
      <value>,</value>
      <webElementGuid>d44b3953-b0c2-426d-93d1-cc38d65342aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>126e4a6a-6984-4f1e-b2bc-b13b75ca71fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modelTSI</value>
      <webElementGuid>3640e647-ca21-4241-bd7e-7d9d9737780b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputTSI</value>
      <webElementGuid>ceeb47ec-c7c8-4f7d-90d2-ebdadcff387d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan TSI / Top Risk</value>
      <webElementGuid>5b5531f7-6eb3-4b38-8790-f6925e1a7ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>265e0b63-65f6-4dfb-8602-a241acfca3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputTSI&quot;)</value>
      <webElementGuid>d266c273-50e0-463d-abcb-7c983a73b55f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputTSI']</value>
      <webElementGuid>7bdf6ee1-d799-48a3-b90b-d0adcaab0e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[3]/fieldset/div/div/input</value>
      <webElementGuid>c9d2aa0d-8dd4-47a7-bb2a-d454a1ed9544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>e375d663-6b5f-4fc8-8aa7-7178d68ca241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'modelTSI' and @id = 'inputTSI' and @placeholder = 'Masukkan TSI / Top Risk']</value>
      <webElementGuid>b298a14c-77be-4d8a-913b-a42742670192</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
