<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StatusAksep</name>
   <tag></tag>
   <elementGuidId>ed934fbb-6642-46e2-90cb-c11170561a52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[normalize-space()='Akseptasi']/following::ng-select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[normalize-space()='Akseptasi']/following::ng-select[1]</value>
      <webElementGuid>d1a5bcad-fb0d-4282-bbe4-2c1b607e479d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
