<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date1</name>
   <tag></tag>
   <elementGuidId>85d3e3bf-d8bc-4185-85d9-1508bb7fcb69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@placeholder='Date'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@placeholder='Date'])[1]</value>
      <webElementGuid>2bab5f03-3c87-4c4b-a6e0-36844a5911e4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
