<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date4</name>
   <tag></tag>
   <elementGuidId>dcd85de3-6989-4645-845d-d53d74d9eeba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@placeholder='Date'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@placeholder='Date'])[1]</value>
      <webElementGuid>b9f09c9d-82b2-40fb-a050-58e894e44976</webElementGuid>
   </webElementProperties>
</WebElementEntity>
