<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputSubjectivityNote</name>
   <tag></tag>
   <elementGuidId>7246af8b-5d08-45db-b00e-356312f75f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='textAreaSubjectivityNote']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;textAreaSubjectivityNote&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea[name=&quot;textAreaSubjectivityNote&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a419906e-b1c3-45f4-9a1b-7ec753156af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textAreaSubjectivityNote</value>
      <webElementGuid>03073b22-734d-4c43-8581-59fb3eec9979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textareaCob ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c6fb7634-b0b5-48dd-b374-2f0dd071eee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMainDashboard&quot;)/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;DivTableContainer DivTableContainerAcceptation&quot;]/table[@class=&quot;TableListDetailsAttachment&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;TableDataInput ng-star-inserted&quot;]/textarea[@class=&quot;textareaCob ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>d837335f-83bb-4f8d-8cd0-556e8a7d2450</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='textAreaSubjectivityNote']</value>
      <webElementGuid>fad6264d-6700-4466-b2d2-286c3378253b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[5]/table/tbody/tr[2]/td[2]/textarea</value>
      <webElementGuid>c10414fa-b1c9-4858-bd62-30734c49bce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/textarea</value>
      <webElementGuid>a088e4e6-315a-428c-bf76-07e142c45ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'textAreaSubjectivityNote']</value>
      <webElementGuid>c6c51bd0-0b45-4672-ba69-5ff957a7f6a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
