<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PilihOJS</name>
   <tag></tag>
   <elementGuidId>8a72c44a-2016-4087-9d45-33c08cb14016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'ng-option')]//span[normalize-space()='OJS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'ng-option')]//span[normalize-space()='OJS']</value>
      <webElementGuid>1c47bc59-b826-4a3b-9f68-9d64118de143</webElementGuid>
   </webElementProperties>
</WebElementEntity>
