<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BurgerMenu</name>
   <tag></tag>
   <elementGuidId>f8307e91-e5a3-45e3-a882-17b4248b23c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonNavigation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buttonNavigation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3bdc0bb-26d9-4ace-9b14-e32754e7b6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52d722c0-9bd6-416e-a243-a4e3d11d05af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonNavigation</value>
      <webElementGuid>d2f7ded0-0c8c-4000-a752-4b2272829b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonNavigation&quot;)</value>
      <webElementGuid>a786403a-8d38-484d-8257-08c380cf8d84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buttonNavigation']</value>
      <webElementGuid>19dd9da4-7940-408b-90b7-2b54e4171b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divBodyHome']/input</value>
      <webElementGuid>06566be0-cf8c-43b0-8ea6-0e4b0ba4221a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>96913f73-d2b2-4f3b-9c18-b1d2d21e6eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'buttonNavigation']</value>
      <webElementGuid>174926b1-cac0-4549-ba4c-bc5e7e2cb55a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
