<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonAttachment</name>
   <tag></tag>
   <elementGuidId>49236043-894e-416f-848b-1300adb1d0d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ButtonAttachment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;1&quot;i] >> internal:role=button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3388f055-bc5b-4ad2-bf51-e3acd3cb639d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4761ede-6a6f-4c95-bdf3-b049a877b056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ButtonAttachment</value>
      <webElementGuid>7f9a6854-1626-419b-9ba4-24edb91de6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DivCOBSubmissionBusiness&quot;)/div[@class=&quot;DivTableContainer DivTableDocument&quot;]/table[@class=&quot;DivLetterTable TableListDetailsAttachment TableForm&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[4]/div[@class=&quot;DivMultipleLabelAttachment&quot;]/label[@class=&quot;LabelAttachment ng-star-inserted&quot;]/input[@class=&quot;ButtonAttachment&quot;]</value>
      <webElementGuid>d7e0a689-36c8-421c-b39c-a22b5c6a33d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='button']</value>
      <webElementGuid>30d733ff-8302-4a67-90e6-876b97bcee19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivCOBSubmissionBusiness']/div/table/tbody/tr/td[4]/div/label/input</value>
      <webElementGuid>93c191c8-7a3e-4937-a03e-345fa25bb1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>efd624ea-8fb1-4851-a8f1-19bca4a9802f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>ecd564a9-deda-44c1-a2b1-e62d8876d35b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
