<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>closeInstallApp</name>
   <tag></tag>
   <elementGuidId>24f26453-9883-4c89-99d7-d477393d87a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonNotificationClose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buttonNotificationClose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8625759-7fc8-4b29-9a02-da41cb29e231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f42d3d3-4427-4f47-8f6b-7cb406b82b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>1f527b5a-4eb3-4b1c-939d-e184a0cdd295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonNotificationClose</value>
      <webElementGuid>32c38392-85c3-4fd9-a84e-3c309d6df044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonNotificationClose&quot;)</value>
      <webElementGuid>f1836d1e-2f6b-4136-aefb-68f8dd5c0600</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buttonNotificationClose']</value>
      <webElementGuid>2634ab47-1ea5-4530-b03c-c25a33aef5a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divNotificationInstall']/input</value>
      <webElementGuid>38eb05ef-5ecc-4c1f-a466-d4a22500d0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>29bd25fc-d1ee-49d9-ad09-9f7e0d125574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'buttonNotificationClose']</value>
      <webElementGuid>c746dce4-005f-47f3-9d57-792ffd55b203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
