<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Departement</name>
   <tag></tag>
   <elementGuidId>19ff7e11-834f-4e5c-86e4-9e8bd307bbc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectModelCOBSubmissionDetailPageDepartementCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectModelCOBSubmissionDetailPageDepartementCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bbd34c4c-beae-4768-ac35-14d3653b97a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPageDepartementCode</value>
      <webElementGuid>d1c2d4cc-643c-4d32-9e65-502eb79d3b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectModelCOBSubmissionDetailPageDepartementCode</value>
      <webElementGuid>48e6de09-98ff-4e99-90ca-b55abf99bdc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-touched</value>
      <webElementGuid>a3812593-0cdd-401f-9560-f8ddacda3db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih DepartementFire &amp; EngineeringMarine, Aviation, Oil &amp; GasFinancial LineWholesaleMiscellaneousDepartement tambahan testtes</value>
      <webElementGuid>4b30e173-0f79-4b4f-9db6-2201fe26b26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectModelCOBSubmissionDetailPageDepartementCode&quot;)</value>
      <webElementGuid>eb3081bf-850a-4785-b058-9e8c44118fbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectModelCOBSubmissionDetailPageDepartementCode']</value>
      <webElementGuid>e543b226-9eca-4eb8-bc14-6ed71428ec18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivCOBSubmissionBusiness']/div/form/div/fieldset/div/div[2]/select</value>
      <webElementGuid>7883d162-acef-406f-95d1-c346a9d5f04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departement*'])[1]/following::select[1]</value>
      <webElementGuid>6b0be3b7-48e0-4712-b43d-cd32a81ce924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lewati Periode'])[1]/following::select[1]</value>
      <webElementGuid>c95e9da3-d47c-4282-997b-908e40e34d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Segment*'])[1]/preceding::select[1]</value>
      <webElementGuid>1f396ba6-80ff-4270-a56d-f1c8f6872d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TSI*'])[1]/preceding::select[2]</value>
      <webElementGuid>7aceae94-685b-49ce-a7ac-7210dbe7c0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>49197924-c982-4b42-859c-63076a52c64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ModelCOBSubmissionDetailPageDepartementCode' and @id = 'selectModelCOBSubmissionDetailPageDepartementCode' and (text() = 'Pilih DepartementFire &amp; EngineeringMarine, Aviation, Oil &amp; GasFinancial LineWholesaleMiscellaneousDepartement tambahan testtes' or . = 'Pilih DepartementFire &amp; EngineeringMarine, Aviation, Oil &amp; GasFinancial LineWholesaleMiscellaneousDepartement tambahan testtes')]</value>
      <webElementGuid>5f425033-5a13-47c8-927c-59ae15b18d1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
