<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Frekuensi Klaim</name>
   <tag></tag>
   <elementGuidId>19584ba7-d449-4c6f-a34e-8e2a62070678</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectModelCOBSubmissionDetailPageClaimFrequency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectModelCOBSubmissionDetailPageClaimFrequency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d9376b41-4d32-4fba-a039-29f40fc2c298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPageClaimFrequency</value>
      <webElementGuid>c335c308-c003-463e-a043-05dc0270d4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectModelCOBSubmissionDetailPageClaimFrequency</value>
      <webElementGuid>fdef0be7-35c3-4c94-a22b-c76fd407e4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>bfe5194f-e2d1-4b98-a7d3-9836b485317b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Frekuensi Klaim01234567891011121314151617181920>20</value>
      <webElementGuid>acb87148-28df-4ecd-bf69-89ee27e61ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectModelCOBSubmissionDetailPageClaimFrequency&quot;)</value>
      <webElementGuid>fb626622-4813-498b-9491-8814c99678de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectModelCOBSubmissionDetailPageClaimFrequency']</value>
      <webElementGuid>2425ebc6-b8dc-4343-83b2-07bd7a08d488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivCOBSubmissionBusiness']/div/form/div/fieldset/div/div[2]/select[3]</value>
      <webElementGuid>f8519b32-546a-43c4-8290-b121a8a26d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frekuensi Klaim'])[1]/following::select[1]</value>
      <webElementGuid>92dc06fc-62d6-4f28-af74-51be13b9f646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loss Record*'])[1]/following::select[1]</value>
      <webElementGuid>4725fde7-b3dc-4abb-b3df-6aa66997df2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loss Improvement*'])[1]/preceding::select[1]</value>
      <webElementGuid>617ce1e3-d596-4b2a-b954-3bda4bb46986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submission Note'])[1]/preceding::select[1]</value>
      <webElementGuid>51945db9-4c0b-4c24-97cd-2fa85622d60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select[3]</value>
      <webElementGuid>02b9c0ee-0652-4004-b717-bda9edd6e356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ModelCOBSubmissionDetailPageClaimFrequency' and @id = 'selectModelCOBSubmissionDetailPageClaimFrequency' and (text() = 'Pilih Frekuensi Klaim01234567891011121314151617181920>20' or . = 'Pilih Frekuensi Klaim01234567891011121314151617181920>20')]</value>
      <webElementGuid>50b9644f-4a5b-4cf8-a7f9-af0d406747f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
