<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputOTP</name>
   <tag></tag>
   <elementGuidId>d8962c2c-c510-4fbd-89ba-7b58bb520305</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passwordEmailToken1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passwordEmailToken1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2028260-2404-4b84-a7d7-f9f7961baa8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4715281a-771c-4424-bc29-1c695e7572f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordEmailToken1</value>
      <webElementGuid>8a61c644-2dda-40cc-949e-b939264e77f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stringEmailToken1</value>
      <webElementGuid>cbe4805c-79b8-4243-8bbf-192c12bdea0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>accff044-2440-48dc-9c1a-b473ec9c4121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>3b04ac9f-c6bb-41af-bec3-eb8cf686ee9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InputToken ng-dirty ng-valid ng-touched</value>
      <webElementGuid>5b19a12b-08c8-4b80-919b-1060dcf2d9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>78bcaf92-e60e-4252-af99-4e08d170f37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordEmailToken1&quot;)</value>
      <webElementGuid>d974dc74-814d-46cd-8bb3-87c5be8ed9a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passwordEmailToken1']</value>
      <webElementGuid>6ea323d8-e893-4a1d-90d3-abd1ff7bf5e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divBodySignIn']/form[2]/div/fieldset/div/input</value>
      <webElementGuid>6de61b96-ca66-4cef-8f95-3dba78f558aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/fieldset/div/input</value>
      <webElementGuid>f00747c6-c89f-48a4-9cb7-7030acc52031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'passwordEmailToken1' and @name = 'stringEmailToken1']</value>
      <webElementGuid>168c65a4-a802-4288-8fc1-40342e1747e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
