<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Share</name>
   <tag></tag>
   <elementGuidId>4ca218bb-6211-462e-89cc-2d2807bdf354</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textModelCOBSubmissionDetailPageSharePercentage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textModelCOBSubmissionDetailPageSharePercentage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a73f0f6-48ad-41ea-aca1-57fdfb287e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e957a5df-7cba-4b0f-b9fa-481e100954f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>3e3deeea-1845-44b2-8b8b-57fc60d174dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPageSharePercentage</value>
      <webElementGuid>dbe1952c-f1cb-49fd-90fe-e4ef0c328744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textModelCOBSubmissionDetailPageSharePercentage</value>
      <webElementGuid>0cbbcbe3-df01-415c-abfa-e9d8c4f52efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Share</value>
      <webElementGuid>9a301da5-3742-47db-99d4-00b1acf955a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-dirty ng-valid ng-touched</value>
      <webElementGuid>94dd12df-805c-44d3-bcf6-c58da530f091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textModelCOBSubmissionDetailPageSharePercentage&quot;)</value>
      <webElementGuid>1b2cc8e9-2013-478b-8aa7-15981a934e55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textModelCOBSubmissionDetailPageSharePercentage']</value>
      <webElementGuid>3298740f-c736-4b42-ac3e-765f379762b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivCOBSubmissionBusiness']/div/form/div/fieldset/div/div[2]/input</value>
      <webElementGuid>dca8116f-6ecd-4f7d-a46e-ee955fe0cb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1739595c-4b71-4976-a939-10a64ff1a854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'ModelCOBSubmissionDetailPageSharePercentage' and @id = 'textModelCOBSubmissionDetailPageSharePercentage' and @placeholder = 'Masukkan Share']</value>
      <webElementGuid>315dc635-ffbe-4fa7-896e-4477a8ba9906</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
