<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputCaptive</name>
   <tag></tag>
   <elementGuidId>40a4b975-89e5-4a17-a9a8-b2856531af5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radioModelCOBSubmissionDetailPageBusinessCaptive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioModelCOBSubmissionDetailPageBusinessCaptive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da6682ce-a15e-4565-8c19-ad42373345df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>694aa4ce-7db7-4488-b985-6780646c3ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPageBusiness</value>
      <webElementGuid>2c2bc79a-c35f-41b7-a051-bdaa8fda4a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioModelCOBSubmissionDetailPageBusinessCaptive</value>
      <webElementGuid>03b8cb17-cd8e-41bf-bd35-4e72a1922ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-touched</value>
      <webElementGuid>a48508ed-7310-4772-be13-37c6296eb8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioModelCOBSubmissionDetailPageBusinessCaptive&quot;)</value>
      <webElementGuid>478263b0-15e0-445a-be86-e7b910be1d3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioModelCOBSubmissionDetailPageBusinessCaptive']</value>
      <webElementGuid>d1338cc3-ffca-4df1-817f-eeef8c1f5d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivCOBSubmissionBusiness']/div/form/div/fieldset/div/div/fieldset[2]/div/label/input</value>
      <webElementGuid>63cb7cba-ad87-46dc-b009-1f22aa87d583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/label/input</value>
      <webElementGuid>2560b41f-da5d-4790-bfff-2a1ef9a54f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ModelCOBSubmissionDetailPageBusiness' and @id = 'radioModelCOBSubmissionDetailPageBusinessCaptive']</value>
      <webElementGuid>06095c5c-c946-48b6-919d-524186166463</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
