<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputEmail</name>
   <tag></tag>
   <elementGuidId>bda7a28b-ad13-4ba1-9bb7-fd668186615a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddb249e7-90f8-410a-9306-47f57d41ad45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e9d0f0ed-332e-46bd-a291-05fc32b5f73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailEmail</value>
      <webElementGuid>502cb800-3f80-454c-9ea6-09a3d38b0194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modelUserEmail</value>
      <webElementGuid>df5bc663-b1d3-4d98-9a67-aab4ce9d2287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>input your employee email</value>
      <webElementGuid>ff8448f7-9690-439b-8d8d-6642e906ff1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>4e996dea-e51f-439b-ac9d-d16e9f6af8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailEmail&quot;)</value>
      <webElementGuid>6c5e199b-e450-4ea8-91c6-0664809ffae7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailEmail']</value>
      <webElementGuid>7529784b-29ee-484a-9de2-b0512d3b1a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divBodySignIn']/form/div/fieldset/div/input</value>
      <webElementGuid>62750441-766d-47dd-b526-7b4fd6608187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>041d53ea-ac11-4d45-9f23-45bfd819fcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'emailEmail' and @name = 'modelUserEmail' and @placeholder = 'input your employee email']</value>
      <webElementGuid>4ab15edd-14ee-483e-b802-45db3bb69414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
