<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lewatiPeriode</name>
   <tag></tag>
   <elementGuidId>4dcf48ce-8354-44ba-90b0-a88ffc40bd3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkboxModelCOBSubmissionDetailPageSkipPeriod</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkboxModelCOBSubmissionDetailPageSkipPeriod']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7a850fe-2d81-49cd-baa8-907484a2637d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0103c2a7-4c84-4535-b5ac-8eb190d06c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPageSkipPeriod</value>
      <webElementGuid>5f2b6c99-7593-478d-a7a7-ac48b6cb1ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkboxModelCOBSubmissionDetailPageSkipPeriod</value>
      <webElementGuid>c508fb86-042a-44ca-be5c-52ca39b521d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1c887239-0765-47ae-9365-ab678cb7d2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>8fc6735b-d988-4280-8037-baec7f157877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkboxModelCOBSubmissionDetailPageSkipPeriod&quot;)</value>
      <webElementGuid>9f1106d6-e946-4512-b7fc-9c4fb4a1eee4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkboxModelCOBSubmissionDetailPageSkipPeriod']</value>
      <webElementGuid>b12cfc5b-bece-4009-a0b0-34b94ac86616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivCOBSubmissionBusiness']/div/form/div/fieldset/div/div/div[3]/label/input</value>
      <webElementGuid>10a51194-fd65-4429-93d5-b9ed1da0263f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/input</value>
      <webElementGuid>7028259f-4798-44d4-967c-790720ad1ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'ModelCOBSubmissionDetailPageSkipPeriod' and @id = 'checkboxModelCOBSubmissionDetailPageSkipPeriod']</value>
      <webElementGuid>7515ca85-534f-4658-815e-ad12535e19c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
