<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>namaSumber</name>
   <tag></tag>
   <elementGuidId>6b2f098a-df3a-4897-bbaf-ae470e33ceb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textModelCOBSubmissionDetailPageBrokerName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textModelCOBSubmissionDetailPageBrokerName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45287a8f-9057-4d88-a8e1-1058deb369bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e754ed30-a472-4180-b880-dcfc6f73e1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPageBrokerName</value>
      <webElementGuid>03af9510-23b9-4ebe-b319-fd16b89f98ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textModelCOBSubmissionDetailPageBrokerName</value>
      <webElementGuid>9ef63aa8-69d7-45ec-b9ec-8934cd6f7a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nama Sumber Bisnis</value>
      <webElementGuid>0ed5ff3b-619c-4df2-a8dc-2ec72ec27708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-star-inserted ng-valid ng-dirty</value>
      <webElementGuid>f0c9fbb0-b8fd-41e8-a376-97135ab24672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textModelCOBSubmissionDetailPageBrokerName&quot;)</value>
      <webElementGuid>7ed416c3-fa70-44d7-b3fb-33549657b492</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textModelCOBSubmissionDetailPageBrokerName']</value>
      <webElementGuid>f95c3cc0-f7c3-40d0-9321-96160ad97ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivCOBSubmissionBusiness']/div/form/div/fieldset/div/div/input[2]</value>
      <webElementGuid>2362f14a-d714-40e5-911f-f6d522277011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>5113a62e-7cfb-4eb7-8d1b-b8b8e4366459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ModelCOBSubmissionDetailPageBrokerName' and @id = 'textModelCOBSubmissionDetailPageBrokerName' and @placeholder = 'Masukkan Nama Sumber Bisnis']</value>
      <webElementGuid>011cddd5-8c2c-41f8-9a3d-b36cea3756e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
