<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>namaDok</name>
   <tag></tag>
   <elementGuidId>121f7bdc-8268-4528-9848-a8befa438bd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textCOBSubmissionDetailPageDocumentName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textCOBSubmissionDetailPageDocumentName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e758de9-1b0c-4df5-bd09-445bd8fb1b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>365f41d8-b69e-4b3f-98b4-e8ba2d448185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPageDocumentName</value>
      <webElementGuid>b1bd9196-5c48-4f56-a47a-5a6068fe4b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textCOBSubmissionDetailPageDocumentName</value>
      <webElementGuid>f2535e1e-b7cc-4a0b-8ea1-d229d6da22bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>14cbabfc-d311-445b-9a15-f30ea8a15203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textCOBSubmissionDetailPageDocumentName&quot;)</value>
      <webElementGuid>8eb4b08a-b12a-4b67-9c42-66d56f6a4ae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textCOBSubmissionDetailPageDocumentName']</value>
      <webElementGuid>94a69a0a-6c84-402a-90db-e7fd516b268c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivCOBSubmissionBusiness']/div/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>b64b8c12-e102-47ae-8d54-b487c8f31434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>da8912e6-f492-403c-b52e-236f1bf69964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ModelCOBSubmissionDetailPageDocumentName' and @id = 'textCOBSubmissionDetailPageDocumentName']</value>
      <webElementGuid>07aa7a1a-1385-4c30-b14a-203114adb580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
