<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nomorPolis</name>
   <tag></tag>
   <elementGuidId>3583b4b5-5564-4192-bf9a-d27b0e15995d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textModelCOBSubmissionDetailPagePolicyNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textModelCOBSubmissionDetailPagePolicyNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74656f20-a42a-4529-9ece-df8a60f75a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0498e49-f2eb-4df6-9854-2d8f41681692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPagePolicyNumber</value>
      <webElementGuid>a80b00bc-c3d1-4d8c-af24-806efbe5509f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textModelCOBSubmissionDetailPagePolicyNumber</value>
      <webElementGuid>d7a4a63b-a7eb-4dd3-bcc4-ddcf9cd8f4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Nomor Polis</value>
      <webElementGuid>2a2b2230-8405-4483-a0d4-576e7559c3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0703f09b-854e-433b-8768-da714b3857f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textModelCOBSubmissionDetailPagePolicyNumber&quot;)</value>
      <webElementGuid>494ab1cc-8f15-4ef0-9c95-0787e280840e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textModelCOBSubmissionDetailPagePolicyNumber']</value>
      <webElementGuid>15e25cc5-43df-4301-bc2f-60e4aaa10358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivCOBSubmissionBusiness']/div/form/div/fieldset/div/div/input[3]</value>
      <webElementGuid>803a9ef9-01ed-4f3e-9031-8816b671c1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>b2fbb87e-29cc-425a-a94c-27dd521beedf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ModelCOBSubmissionDetailPagePolicyNumber' and @id = 'textModelCOBSubmissionDetailPagePolicyNumber' and @placeholder = 'Masukkan Nomor Polis']</value>
      <webElementGuid>018203df-f11f-4658-aa90-57a055cfd070</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
