<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Non-Captive</name>
   <tag></tag>
   <elementGuidId>76ecd7b1-f4d1-419d-ad63-8ab4fe4254a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radioModelCOBSubmissionDetailPageBusinessNonCaptive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioModelCOBSubmissionDetailPageBusinessNonCaptive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5fd4065-ab02-4af6-a742-5332cb49d0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a7a96e3b-1a33-43e5-8209-236a5c576357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPageBusiness</value>
      <webElementGuid>1b61d9d8-74a9-492e-a8a8-f00810bee85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioModelCOBSubmissionDetailPageBusinessNonCaptive</value>
      <webElementGuid>15ff055d-2d2b-4375-8b0f-246df05017a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-touched</value>
      <webElementGuid>1e4ac282-ee9a-4abf-b670-397fe390fbcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioModelCOBSubmissionDetailPageBusinessNonCaptive&quot;)</value>
      <webElementGuid>9c3514b2-7d8f-48fc-b57b-0147b6d5a1bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioModelCOBSubmissionDetailPageBusinessNonCaptive']</value>
      <webElementGuid>82c537dc-1a41-419b-8515-809036c8b8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivCOBSubmissionBusiness']/div/form/div/fieldset/div/div/fieldset[2]/div/label[2]/input</value>
      <webElementGuid>1dac7fc5-e4d8-44e6-ae76-43c1a796371e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/label[2]/input</value>
      <webElementGuid>5e28089a-7bdb-47f4-8e46-cc95916c9047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ModelCOBSubmissionDetailPageBusiness' and @id = 'radioModelCOBSubmissionDetailPageBusinessNonCaptive']</value>
      <webElementGuid>29f09479-3a5e-4a26-a10a-d0760cadbb2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
