<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Segment</name>
   <tag></tag>
   <elementGuidId>42b71115-c682-4770-8c93-b37558e437ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectModelCOBSubmissionDetailPageSegmentDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectModelCOBSubmissionDetailPageSegmentDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1ac617cc-5f48-499a-b683-ed788826a9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPageSegmentDescription</value>
      <webElementGuid>57296303-4eea-4497-9433-961fcea9542c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectModelCOBSubmissionDetailPageSegmentDescription</value>
      <webElementGuid>c1d89b28-b170-48a2-9fab-b15f4ff4e0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>03c8c0de-f3a2-45ad-8f65-3015fccc752c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih SegmenA3KOLAKUAALLIANCESBANCASSURANCECORPORATEDIRECT RESPONSEINDIVIDUALMIKRONOT AVAILABLENON A3KOLRETAILTELE MARKETINGTURUNAN CAPTIVEWHOLESALE</value>
      <webElementGuid>e3886f26-d99c-4e30-8fa7-93b71aad31e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectModelCOBSubmissionDetailPageSegmentDescription&quot;)</value>
      <webElementGuid>7f550a1f-d6e3-4ff7-858c-49cc4d036392</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectModelCOBSubmissionDetailPageSegmentDescription']</value>
      <webElementGuid>9fb75dfc-15b8-4dd9-839c-d0f0418168c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivCOBSubmissionBusiness']/div/form/div/fieldset/div/div[2]/select[2]</value>
      <webElementGuid>efec3f42-e2db-4037-9138-9c92942adbb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Segment*'])[1]/following::select[1]</value>
      <webElementGuid>dca3a019-a615-4e0c-ae3a-e11d6b9c6204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departement*'])[1]/following::select[2]</value>
      <webElementGuid>0da2f9f2-a77c-401f-a3d3-7a69514b3a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TSI*'])[1]/preceding::select[1]</value>
      <webElementGuid>f009639b-7540-4b99-81a1-dd52ed19b883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share (%)*'])[1]/preceding::select[2]</value>
      <webElementGuid>48d88906-ca83-40b1-b9fc-c41a8b7c9910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select[2]</value>
      <webElementGuid>67ddd279-93cc-49f3-a58a-f5815feff02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ModelCOBSubmissionDetailPageSegmentDescription' and @id = 'selectModelCOBSubmissionDetailPageSegmentDescription' and (text() = 'Pilih SegmenA3KOLAKUAALLIANCESBANCASSURANCECORPORATEDIRECT RESPONSEINDIVIDUALMIKRONOT AVAILABLENON A3KOLRETAILTELE MARKETINGTURUNAN CAPTIVEWHOLESALE' or . = 'Pilih SegmenA3KOLAKUAALLIANCESBANCASSURANCECORPORATEDIRECT RESPONSEINDIVIDUALMIKRONOT AVAILABLENON A3KOLRETAILTELE MARKETINGTURUNAN CAPTIVEWHOLESALE')]</value>
      <webElementGuid>012ce0ad-3a56-4fe6-a40c-5fd2ce680dc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
