<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StatusPenutupan</name>
   <tag></tag>
   <elementGuidId>44f4e776-2c28-41cb-8921-656043e5575a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectModelCOBSubmissionDetailPageClosingStatusCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectModelCOBSubmissionDetailPageClosingStatusCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9a95d27e-ab3a-4a27-82f4-4be6189e8e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPageClosingStatusCode</value>
      <webElementGuid>9714301b-f2db-4971-bc35-482ac2e31f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectModelCOBSubmissionDetailPageClosingStatusCode</value>
      <webElementGuid>51f270de-9a1c-4e81-99dc-97cf12144914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-valid ng-touched</value>
      <webElementGuid>f3045c30-1a72-412d-b66d-7cad2b1f2f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Status PenutupanNewEndorsmentRenewalCancelation</value>
      <webElementGuid>05f0c0de-1c28-41e2-bf43-2e08359127f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectModelCOBSubmissionDetailPageClosingStatusCode&quot;)</value>
      <webElementGuid>0c519bf3-ab39-4aad-84e8-9abb5416d8f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectModelCOBSubmissionDetailPageClosingStatusCode']</value>
      <webElementGuid>e216181e-b739-4c09-adb1-7676218b8b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivCOBSubmissionBusiness']/div/form/div/fieldset/div/div/select[3]</value>
      <webElementGuid>6312b177-4d09-4735-806d-0edc55b6b99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Penutupan*'])[1]/following::select[1]</value>
      <webElementGuid>e4481311-95a6-4aff-b669-f187b3933737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aviation Hull'])[1]/following::select[1]</value>
      <webElementGuid>7cfc34b4-c153-45df-8b28-d58bfc6c6795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Polis*'])[1]/preceding::select[1]</value>
      <webElementGuid>e2c7efa2-f80e-44ef-9851-23acf04ded64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tertanggung*'])[1]/preceding::select[1]</value>
      <webElementGuid>5381f875-c5c6-4738-bb4e-3713fe882715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[3]</value>
      <webElementGuid>1aa16d0e-a996-4a45-a332-b5469b5c3f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ModelCOBSubmissionDetailPageClosingStatusCode' and @id = 'selectModelCOBSubmissionDetailPageClosingStatusCode' and (text() = 'Pilih Status PenutupanNewEndorsmentRenewalCancelation' or . = 'Pilih Status PenutupanNewEndorsmentRenewalCancelation')]</value>
      <webElementGuid>e948cd50-7ea1-420c-9b00-437c1cf0b156</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
