<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Submission Note</name>
   <tag></tag>
   <elementGuidId>dbcda98e-ffa7-4b8d-8754-39e554257d2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#textModelCOBSubmissionDetailPageSubmissionNote</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='textModelCOBSubmissionDetailPageSubmissionNote']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4bf41a9e-6b90-42ac-baa1-9bfb0f369db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPageSubmissionNote</value>
      <webElementGuid>77abd5d5-7d6c-411b-85db-803328bfac95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textModelCOBSubmissionDetailPageSubmissionNote</value>
      <webElementGuid>242c3587-a858-4fc8-ac90-607c3a49942c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukan Catatan</value>
      <webElementGuid>da970a77-4972-40fe-b01b-e52825c97443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>d90aaf3c-b2d7-4f94-824a-7882d8fe6ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textModelCOBSubmissionDetailPageSubmissionNote&quot;)</value>
      <webElementGuid>aed36564-8924-4d28-b970-fc2ab92edb3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='textModelCOBSubmissionDetailPageSubmissionNote']</value>
      <webElementGuid>a421d278-75a1-4f27-b45d-9ddfd87705dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div/fieldset/textarea</value>
      <webElementGuid>717fd3d8-a46f-4685-897f-553ba0fa1f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/textarea</value>
      <webElementGuid>6f83898a-84fa-4a29-af7b-d9b882eb8d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ModelCOBSubmissionDetailPageSubmissionNote' and @id = 'textModelCOBSubmissionDetailPageSubmissionNote' and @placeholder = 'Masukan Catatan']</value>
      <webElementGuid>90429959-bf39-4bfb-ab07-652a19a17b38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
