<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TSI_Currency</name>
   <tag></tag>
   <elementGuidId>22038769-42bc-483f-8bd9-1a36afab20fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectModelCOBSubmissionDetailPageCurrency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectModelCOBSubmissionDetailPageCurrency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>701cd6ba-ebee-4997-9e4b-6258fb45b3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPageCurrency</value>
      <webElementGuid>651fe211-8451-4ab8-85a0-855af7c03cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectModelCOBSubmissionDetailPageCurrency</value>
      <webElementGuid>6fd63f3b-e105-4722-bedc-fe4daa8b7d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>17a1a170-38fb-467a-9702-931edf9472a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih CurrencyIDRUSDEURJPYGBPAUDCAD</value>
      <webElementGuid>ee4c1867-69f3-4bab-bd68-69f2834b5c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectModelCOBSubmissionDetailPageCurrency&quot;)</value>
      <webElementGuid>d4a1d72c-e601-451e-bc03-476836fc76a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectModelCOBSubmissionDetailPageCurrency']</value>
      <webElementGuid>7acf14a1-35ea-41c3-af69-cfd9ae4d6839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivCOBSubmissionBusiness']/div/form/div/fieldset/div/div[2]/div/select</value>
      <webElementGuid>35438b22-f5bd-4f7a-81f6-ca745b9b6aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TSI*'])[1]/following::select[1]</value>
      <webElementGuid>d2d1c01b-9adb-46ee-975c-540892d2a56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Segment*'])[1]/following::select[2]</value>
      <webElementGuid>8f27921e-ccd9-4b2d-9952-48dc75b72fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share (%)*'])[1]/preceding::select[1]</value>
      <webElementGuid>d1204b30-4661-4eaf-82ca-13b647de3f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TSI x Share*'])[1]/preceding::select[1]</value>
      <webElementGuid>ccac6469-ccdf-4f01-accc-f9015675de54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>da4a05c1-6c28-493b-a78b-22da757f5ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ModelCOBSubmissionDetailPageCurrency' and @id = 'selectModelCOBSubmissionDetailPageCurrency' and (text() = 'Pilih CurrencyIDRUSDEURJPYGBPAUDCAD' or . = 'Pilih CurrencyIDRUSDEURJPYGBPAUDCAD')]</value>
      <webElementGuid>cbd429bd-fbed-400f-8f42-c46cf8a0588c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
