<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBoxDecision6</name>
   <tag></tag>
   <elementGuidId>e75da0bc-8c60-4591-be94-653febc32d15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkBoxDecision5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkBoxDecision5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#checkBoxDecision5</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>705a29f8-e008-470f-9e6e-9d13abfbd20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f66fe4d8-9aa3-446d-86d9-b3de7dcbece8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkBoxDecision5</value>
      <webElementGuid>1d5eb6a3-517f-4ea2-ada7-a2db83e680b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkBoxDecision5</value>
      <webElementGuid>709ad04b-b576-45b5-ab61-972f0e24e215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>e92cd8a3-da6c-4638-bde1-2b35180338d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkBoxDecision5&quot;)</value>
      <webElementGuid>cd9c09a4-ef21-4a78-baa0-cf9e57772b0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkBoxDecision5']</value>
      <webElementGuid>4440ed9e-e3fa-4806-9bd2-a7d93a5f9fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[14]/table/tbody/tr[6]/td/input</value>
      <webElementGuid>6dca0064-cd3f-4376-9b88-47c4c47851e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/input</value>
      <webElementGuid>7304aead-139f-457d-b425-2aff1e4d636d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'checkBoxDecision5' and @id = 'checkBoxDecision5']</value>
      <webElementGuid>e53428ef-01cb-4662-9ed6-1227ed43a875</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
