<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DropdownDisposisi</name>
   <tag></tag>
   <elementGuidId>b580b786-c847-44bc-b8d8-2fcda01b06b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ng-select[@id='selectStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ng-select[@id='selectStatus']</value>
      <webElementGuid>658228cf-aa41-4a87-9997-5834e3e92fbb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
