<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonDeleteRound</name>
   <tag></tag>
   <elementGuidId>af3709c3-b313-4cab-a163-7f2f6e4d0095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='button'])[34]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.DivTableContainer.DivTableContainerAcceptation.ng-star-inserted > table.TableListDetailsAttachment > tbody > tr.ng-star-inserted > td:nth-of-type(6) > div.DivMultipleLabelAttachment > label.LabelAttachment.ng-star-inserted > input.ButtonDeleteRound</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Masukkan Nama Document -&quot;i] >> internal:label=&quot;&quot;i >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a129ce1b-765b-498b-aeb3-90a0e6807965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3cbcc2a2-e532-4cba-9179-c097c90c65b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ButtonDeleteRound</value>
      <webElementGuid>c98811cb-86d2-4b5a-b852-1021241a04ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMainDashboard&quot;)/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;DivTableContainer DivTableContainerAcceptation ng-star-inserted&quot;]/table[@class=&quot;TableListDetailsAttachment&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[6]/div[@class=&quot;DivMultipleLabelAttachment&quot;]/label[@class=&quot;LabelAttachment ng-star-inserted&quot;]/input[@class=&quot;ButtonDeleteRound&quot;]</value>
      <webElementGuid>bdb78192-11a5-43aa-a683-6220ba89817b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='button'])[34]</value>
      <webElementGuid>a370859a-c98d-43a2-914c-d24b68429da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[14]/table/tbody/tr/td[6]/div/label[3]/input</value>
      <webElementGuid>62aba460-c299-48d7-97b7-cd4b9b8a2850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/table/tbody/tr/td[6]/div/label[3]/input</value>
      <webElementGuid>24cfa9b9-4563-44e7-9d0b-e73745f13dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>d119cb53-1ce5-471f-9dd0-1af45fe94d69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
