<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lampiran Dokumen Putusan_checkBoxDecision</name>
   <tag></tag>
   <elementGuidId>e4769ef3-acf4-42c9-a1ce-85a1163d9349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkBoxDecision']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkBoxDecision</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#checkBoxDecision</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbd44995-45c2-4d67-a260-75bfe7283df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>eb152842-ad2f-42d0-86c7-a221b53d34b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkBoxDecision</value>
      <webElementGuid>28b6ea4e-81c1-4121-9966-ac8661e8f01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkBoxDecision</value>
      <webElementGuid>42b1748d-983f-4fc5-b575-da0cab18603a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>457fd435-7523-46f4-90cf-cab24cbe7025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkBoxDecision&quot;)</value>
      <webElementGuid>c6935d4a-7168-4044-95dd-13da517ea56a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkBoxDecision']</value>
      <webElementGuid>74ef97ba-e59d-4c0e-8bd3-f9522f32bc4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[14]/table/thead/tr/th/div/input</value>
      <webElementGuid>bda43c36-8f3a-43aa-9c54-47dd8b4fc9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/table/thead/tr/th/div/input</value>
      <webElementGuid>4a746e42-787c-41aa-8c27-c99c241ab368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'checkBoxDecision' and @id = 'checkBoxDecision']</value>
      <webElementGuid>ca502cc8-516b-4afc-b3e3-f6a57555bc13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
