<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textAreaSubjectivityNote</name>
   <tag></tag>
   <elementGuidId>a192ccc0-333d-4bf0-b3a5-749795cd2439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='textAreaSubjectivityNote']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;textAreaSubjectivityNote&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>textarea[name=&quot;textAreaSubjectivityNote&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fdd32391-085b-4471-b82b-3581cd0c3937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>textAreaSubjectivityNote</value>
      <webElementGuid>da028806-318a-4e9b-b1a3-1c2b8746b7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textareaCob ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4b86aeb7-0faa-4df2-b9eb-f823bb260014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMainDashboard&quot;)/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;DivTableContainer DivTableContainerAcceptation&quot;]/table[@class=&quot;TableListDetailsAttachment&quot;]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;TableDataInput ng-star-inserted&quot;]/textarea[@class=&quot;textareaCob ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>1636342e-8285-42e2-bd6f-678b308139d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='textAreaSubjectivityNote']</value>
      <webElementGuid>8da949be-2721-483c-bb1a-60b3efefc480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[5]/table/tbody/tr[3]/td[2]/textarea</value>
      <webElementGuid>890285cd-1fc5-446e-92ef-a36b495f8ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/textarea</value>
      <webElementGuid>818511ba-1be1-42d2-b171-c59d8e5cc509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'textAreaSubjectivityNote']</value>
      <webElementGuid>df0c9b25-7c61-4698-bbfb-7725a4d15df3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
