<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputRICommSurplus</name>
   <tag></tag>
   <elementGuidId>071088fc-ee89-49b5-bcdd-e259b6f014a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputRICommSurplus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputRICommSurplus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e9d4ba1-0962-4ec4-b992-a3298c8a7d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb206e82-31b0-4a90-8279-5c5f8ac49e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>separator.6</value>
      <webElementGuid>571e3f94-fea5-4a02-ae1a-f51521f45b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thousandseparator</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>6787fe5a-6dac-4d50-a4a6-27af46f645b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalmarker</name>
      <type>Main</type>
      <value>,</value>
      <webElementGuid>fdd70ae1-495d-48d9-b623-82219e45dedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>bb2f6b00-a8c0-4093-91c6-6e4d836a88b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modelRICommSurplus</value>
      <webElementGuid>6c677a8b-c865-4c6d-95d7-9890658a65ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputRICommSurplus</value>
      <webElementGuid>22e24d25-b1e1-4852-9b7c-fd68099a1e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Angka</value>
      <webElementGuid>dacf1484-2a94-477d-a330-bacc969d1e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c6b57701-d35b-467c-9d96-45d8b95c2e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputRICommSurplus&quot;)</value>
      <webElementGuid>6017ee05-59d3-4ae3-9140-2e43319651a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputRICommSurplus']</value>
      <webElementGuid>0608d61f-3566-449d-94b3-264c1ea2ab6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[3]/fieldset/div/div[2]/div/div[2]/input</value>
      <webElementGuid>35f85e13-ed6a-487a-b0da-65cf5124eb71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>9be66d39-757a-4230-9003-e67a14a27ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'modelRICommSurplus' and @id = 'inputRICommSurplus' and @placeholder = 'Masukkan Angka']</value>
      <webElementGuid>453df721-1632-4507-8336-d1f752d4aeda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
