<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputSurplus</name>
   <tag></tag>
   <elementGuidId>95bc8bd9-8fd3-4c59-b36c-97031aee5f80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='modelSurplus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;modelSurplus&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b0ac1c8-200e-4e94-a56b-b5549f75b36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>781f665e-754d-4649-a46e-33fc03a0584b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>separator.6</value>
      <webElementGuid>8599d0bb-905b-4b28-be4a-bd9ea58366b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thousandseparator</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>24ec2782-e95d-4567-b811-4f514cb3f2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalmarker</name>
      <type>Main</type>
      <value>,</value>
      <webElementGuid>94a218f8-75f5-4870-8e80-495e5577476b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>89a19a82-f193-44db-9872-9b53717f3c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>modelSurplus</value>
      <webElementGuid>18acad05-1307-4300-80c8-59ea6088c5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Surplus</value>
      <webElementGuid>db8fa208-f1e8-40bc-94a0-4cc4358566b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b835871c-6138-4a94-9601-5836dbef97a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMainDashboard&quot;)/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;DivForm ng-star-inserted&quot;]/fieldset[1]/div[@class=&quot;DivFormHorizontalContainer&quot;]/div[@class=&quot;DivForm2Column&quot;]/div[@class=&quot;DivFormKapasityTreaty&quot;]/div[@class=&quot;DivFirstInput&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>808c00ab-6e7f-4589-a16d-011c993708c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='modelSurplus']</value>
      <webElementGuid>3f6fb397-3d3d-4795-818b-91cbbbe0b16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[3]/fieldset/div/div[2]/div/div/input</value>
      <webElementGuid>30f89e4a-e8a3-4e8c-92b9-d9ce461b2c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>b74946f2-dc84-4bda-b14b-9f00e7dc53b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'modelSurplus' and @placeholder = 'Masukkan Surplus']</value>
      <webElementGuid>d28ab250-300d-49fd-8990-747cba0a3406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
