<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnEnter</name>
   <tag></tag>
   <elementGuidId>1a3c03fb-d796-4dd7-81bf-66bda538c9a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Enter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4fbedc1-528f-4fcb-8a96-6cb43611dfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d142fb2c-e52e-437a-8b84-5b9c7ecfd297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>c93f523c-092a-4659-802c-04d5079f8e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divBodySignIn&quot;)/form[@class=&quot;FormSignInHide ng-pristine ng-valid ng-touched&quot;]/input[1]</value>
      <webElementGuid>b6d4b1a1-f677-4d6a-94c0-14ded2199ec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Enter']</value>
      <webElementGuid>17664c98-d352-4fd9-b105-17d81fa04c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divBodySignIn']/form/input</value>
      <webElementGuid>c85f6b9d-b7a9-4a4a-8e3d-6fd569a8bc59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>ec5b23a7-3fd3-4d29-aeec-109640d4da65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>afba0813-15e7-4357-83fa-3871a26e0e90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
