<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Pengiriman</name>
   <tag></tag>
   <elementGuidId>8fb6bddb-945c-471f-8b46-873795ab528e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='textModelCOBSubmissionDetailPagePolicyCoveringNote']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#textModelCOBSubmissionDetailPagePolicyCoveringNote</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Masukkan Alamat&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11354230-8625-4aad-a730-7c3a862ffc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b7c076c-a2df-4a7b-b9c2-9ea49d9216e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ModelCOBSubmissionDetailPagePolicyCoveringNote</value>
      <webElementGuid>1edd26fc-0d86-4c82-9191-4bf1411be1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textModelCOBSubmissionDetailPagePolicyCoveringNote</value>
      <webElementGuid>710c066f-c928-46b0-bf9d-610b4726c6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Alamat</value>
      <webElementGuid>edb954da-3986-465a-9445-a240940d0b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>517be13f-48c2-4b31-915e-ad545ba17a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;textModelCOBSubmissionDetailPagePolicyCoveringNote&quot;)</value>
      <webElementGuid>9fd33c86-6f7f-4f65-8554-fc2d133a671f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='textModelCOBSubmissionDetailPagePolicyCoveringNote']</value>
      <webElementGuid>45d58f73-1bbf-47ae-81ca-6e5cc6336dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DivCOBSubmissionBusiness']/div/div[6]/div[2]/form/div/fieldset/div[2]/div[2]/input</value>
      <webElementGuid>03d0d479-28b0-45d9-98de-a7c56c5c81b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1c5b0cdd-6199-4e65-9cf3-a89f2ef80a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ModelCOBSubmissionDetailPagePolicyCoveringNote' and @id = 'textModelCOBSubmissionDetailPagePolicyCoveringNote' and @placeholder = 'Masukkan Alamat']</value>
      <webElementGuid>7d2cdd35-a513-4a3d-8f19-cf01cf3bed8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
