<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AttachmentDocUnder</name>
   <tag></tag>
   <elementGuidId>4cecd7c5-9326-434a-a69d-1c654247e0c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fileAttachmentClosed']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fileAttachmentClosed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fa57471-6313-4762-9bdc-93c5f3cca39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>153ea4ab-d5f0-45f9-bf2e-83c282daf72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fileAttachmentClosed</value>
      <webElementGuid>bf3abb07-c660-4936-9fa0-23d89b5396fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ButtonAttachment</value>
      <webElementGuid>2892d183-67bb-453a-9aaa-0baecd1e43e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileAttachmentClosed&quot;)</value>
      <webElementGuid>b7284b8c-2ca5-4f7e-9884-7e9e6e70da80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fileAttachmentClosed']</value>
      <webElementGuid>0ddac83a-234c-4965-9439-fbe2ab7403d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[7]/table/tbody/tr/td[6]/div/label/input[2]</value>
      <webElementGuid>c90c9835-f916-4875-994c-a8cfb0c92eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/label/input[2]</value>
      <webElementGuid>3e18ded0-d6c8-4c34-bb1a-89cc22b194bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'fileAttachmentClosed']</value>
      <webElementGuid>b636c0e3-a807-4f3e-90c0-4f8186019f53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
