<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonSendUnder</name>
   <tag></tag>
   <elementGuidId>ef112200-b15c-40fc-a5e9-d4c997e8db96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='button'])[7]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-home/div/main/app-productclassofbusinessdetailunderwriting/div/div/form/div[7]/table/tbody/tr/td[6]/div/label[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(6) > div.DivMultipleLabelAttachment > label.LabelAttachment.ng-star-inserted > input.ButtonSend</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-home/div/main/app-productclassofbusinessdetailunderwriting/div/div/form/div[7]/table/tbody/tr/td[6]/div/label[2]/input</value>
      <webElementGuid>f0fcea20-7179-48d8-96ae-a570f8abebaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='button'])[7]</value>
      <webElementGuid>3a575a2a-88f2-4d81-a43e-850c8e5f3581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/form/div[7]/table/tbody/tr/td[6]/div/label[2]/input</value>
      <webElementGuid>fe6891bc-bb79-40c1-989f-5af4184a804c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/label[2]/input</value>
      <webElementGuid>46ae40e5-0569-421c-97c9-44f15d5f4497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>54a90610-478d-486f-9e89-1589da6f6ab5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
