<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubDetail By Ria Approval Polis</name>
   <tag></tag>
   <elementGuidId>db8bb526-b58d-4781-bd29-93da6147eefa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divMainDashboard']/div/table/tbody/tr[9]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;BN57/1861/UND/WS-0114/SMG/11/25&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0caf0379-6005-43f4-bea5-fd51560fde68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BN57/1861/UND/WS-0114/SMG/11/25</value>
      <webElementGuid>0a236e3d-d309-4a58-a9c6-fbc32481bdf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMainDashboard&quot;)/div[@class=&quot;DivTableContainer&quot;]/table[1]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[2]</value>
      <webElementGuid>36475867-f1d2-4de0-a3e5-29b899f27c83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMainDashboard']/div/table/tbody/tr[9]/td[2]</value>
      <webElementGuid>f6ac877f-0acf-44bc-b480-0b1a7389464e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waiting checking / Inforce policy'])[8]/following::td[2]</value>
      <webElementGuid>6d4f90b6-3099-4053-9339-255e1c05baca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test BARU BRINSMART'])[1]/following::td[5]</value>
      <webElementGuid>94847851-946a-42d4-b5d7-c51582f0ccb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[5]/preceding::td[1]</value>
      <webElementGuid>7d7bd3d6-be75-4178-9ff3-093d88b3ada3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Automation QA2'])[1]/preceding::td[2]</value>
      <webElementGuid>42f7f9c4-4ffd-4292-b1fa-86f9491410d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BN57/1861/UND/WS-0114/SMG/11/25']/parent::*</value>
      <webElementGuid>26a978ba-c37c-42f9-9118-2bb0f10106d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]</value>
      <webElementGuid>2529a8be-eab3-454f-9744-0f86f09de742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'BN57/1861/UND/WS-0114/SMG/11/25' or . = 'BN57/1861/UND/WS-0114/SMG/11/25')]</value>
      <webElementGuid>b7fd7306-d2ac-47cc-bbee-deab7d6fd4be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
